apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: operatorhubio
  namespace: operatorhubio-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: operatorhubio
          servicePort: 8080
